name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repsitory
        uses: actions/checkout@v3

      - run: git branch
      - run: ls -al
      - run: pwd
      - run: ls -la /home/runner/work/driva-app
      - run: ls -la /home/runner/work/driva-app/driva-app
      - run: cd /home/runner/work/driva-app/driva-app/driva-app

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install /home/runner/work/driva-app/driva-app/driva-app

      - run: cat /home/runner/work/driva-app/driva-app/driva-app/package.json

      - name: build
        run: npm run build
        working-directory: driva-app

      - run: cd /home/runner/work/driva-app/driva-app/driva-app
      - run: pwd

      - run: cat /home/runner/work/driva-app/driva-app/driva-app/firebase.json

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DRIVA_TEST_6BA52 }}'
          channelId: live
          projectId: driva-test-6ba52
      - name: List directory contents
        run: ls -R